# Generated by Django 5.2.9 on 2025-12-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='occured_at',
            new_name='occurred_at',
        ),
    ]
